//
//  HistoryView.swift
//  Operator
//
//  Historical trends, session reports, and data export view.
//

import SwiftUI
import Charts

struct HistoryView: View {
    @StateObject private var historyStore = HistoryStore.shared
    @State private var selectedRange: TimeRange = .lastHour
    @State private var selectedMetric: HistoryMetric = .cpu
    @State private var showExportSheet = false
    @State private var showSessionDetails: SessionSummary?

    var body: some View {
        ScrollView {
            VStack(spacing: 16) {
                // Time range selector
                TimeRangeSelector(selectedRange: $selectedRange)

                // Main chart
                HistoryChartPanel(
                    dataPoints: historyStore.getAggregatedData(for: selectedRange),
                    selectedMetric: $selectedMetric
                )

                // Statistics
                StatisticsPanel(dataPoints: historyStore.getData(for: selectedRange))

                // Session reports
                SessionReportsPanel(
                    sessions: historyStore.sessions,
                    onSelect: { session in
                        showSessionDetails = session
                    }
                )

                // Export section
                ExportPanel(
                    selectedRange: selectedRange,
                    onExport: { format in
                        exportData(format: format)
                    }
                )
            }
            .padding()
        }
        .sheet(item: $showSessionDetails) { session in
            SessionDetailView(session: session)
        }
    }

    private func exportData(format: ExportFormat) {
        switch format {
        case .csv:
            let csv = historyStore.exportToCSV(range: selectedRange)
            saveToFile(content: csv, filename: "operator_metrics.csv", type: "csv")
        case .json:
            if let json = historyStore.exportToJSON(range: selectedRange) {
                saveToFile(data: json, filename: "operator_metrics.json", type: "json")
            }
        case .clipboard:
            let summary = generateSummary()
            NSPasteboard.general.clearContents()
            NSPasteboard.general.setString(summary, forType: .string)
        }
    }

    private func saveToFile(content: String, filename: String, type: String) {
        let panel = NSSavePanel()
        panel.nameFieldStringValue = filename
        panel.allowedContentTypes = [.init(filenameExtension: type)!]

        if panel.runModal() == .OK, let url = panel.url {
            try? content.write(to: url, atomically: true, encoding: .utf8)
        }
    }

    private func saveToFile(data: Data, filename: String, type: String) {
        let panel = NSSavePanel()
        panel.nameFieldStringValue = filename
        panel.allowedContentTypes = [.init(filenameExtension: type)!]

        if panel.runModal() == .OK, let url = panel.url {
            try? data.write(to: url)
        }
    }

    private func generateSummary() -> String {
        let data = historyStore.getData(for: selectedRange)
        guard !data.isEmpty else { return "No data available" }

        let avgCPU = data.map(\.cpuUsage).reduce(0, +) / Double(data.count)
        let maxCPU = data.map(\.cpuUsage).max() ?? 0
        let avgMem = data.map(\.memoryUsage).reduce(0, +) / Double(data.count)
        let maxMem = data.map(\.memoryUsage).max() ?? 0

        return """
        Operator System Metrics Summary
        Time Range: \(selectedRange.rawValue)
        Data Points: \(data.count)

        CPU Usage:
        - Average: \(String(format: "%.1f%%", avgCPU))
        - Maximum: \(String(format: "%.1f%%", maxCPU))

        Memory Usage:
        - Average: \(String(format: "%.1f%%", avgMem))
        - Maximum: \(String(format: "%.1f%%", maxMem))

        Generated by Operator
        """
    }
}

// MARK: - History Metric

enum HistoryMetric: String, CaseIterable {
    case cpu = "CPU"
    case memory = "Memory"
    case network = "Network"
    case disk = "Disk I/O"

    var color: Color {
        switch self {
        case .cpu: return .blue
        case .memory: return .green
        case .network: return .orange
        case .disk: return .purple
        }
    }
}

// MARK: - Export Format

enum ExportFormat: String, CaseIterable {
    case csv = "CSV"
    case json = "JSON"
    case clipboard = "Copy Summary"

    var icon: String {
        switch self {
        case .csv: return "tablecells"
        case .json: return "curlybraces"
        case .clipboard: return "doc.on.clipboard"
        }
    }
}

// MARK: - Time Range Selector

struct TimeRangeSelector: View {
    @Binding var selectedRange: TimeRange

    var body: some View {
        HStack(spacing: 8) {
            ForEach(TimeRange.allCases.filter { $0 != .custom }) { range in
                Button(range.rawValue) {
                    selectedRange = range
                }
                .buttonStyle(.borderless)
                .padding(.horizontal, 12)
                .padding(.vertical, 6)
                .background(
                    selectedRange == range
                        ? Color.accentColor.opacity(0.2)
                        : Color.primary.opacity(0.05)
                )
                .foregroundColor(selectedRange == range ? .accentColor : .primary)
                .cornerRadius(6)
                .contentShape(Rectangle())
            }
        }
    }
}

// MARK: - History Chart Panel

struct HistoryChartPanel: View {
    let dataPoints: [MetricDataPoint]
    @Binding var selectedMetric: HistoryMetric

    var body: some View {
        GlassPanel(title: "Trends", icon: "chart.line.uptrend.xyaxis") {
            VStack(spacing: 12) {
                // Metric selector
                HStack(spacing: 8) {
                    ForEach(HistoryMetric.allCases, id: \.self) { metric in
                        Button(metric.rawValue) {
                            selectedMetric = metric
                        }
                        .buttonStyle(.borderless)
                        .padding(.horizontal, 10)
                        .padding(.vertical, 4)
                        .background(
                            selectedMetric == metric
                                ? metric.color.opacity(0.2)
                                : Color.clear
                        )
                        .foregroundColor(selectedMetric == metric ? metric.color : .secondary)
                        .cornerRadius(4)
                        .contentShape(Rectangle())
                    }
                    Spacer()
                }

                // Chart
                if dataPoints.isEmpty {
                    Text("Collecting data...")
                        .font(.caption)
                        .foregroundColor(.secondary)
                        .frame(height: 200)
                } else {
                    Chart {
                        ForEach(dataPoints) { point in
                            LineMark(
                                x: .value("Time", point.timestamp),
                                y: .value("Value", valueForMetric(point))
                            )
                            .foregroundStyle(selectedMetric.color)

                            AreaMark(
                                x: .value("Time", point.timestamp),
                                y: .value("Value", valueForMetric(point))
                            )
                            .foregroundStyle(
                                LinearGradient(
                                    colors: [selectedMetric.color.opacity(0.3), selectedMetric.color.opacity(0.05)],
                                    startPoint: .top,
                                    endPoint: .bottom
                                )
                            )
                        }
                    }
                    .chartYAxis {
                        AxisMarks(position: .leading)
                    }
                    .chartXAxis {
                        AxisMarks(values: .automatic(desiredCount: 5))
                    }
                    .frame(height: 200)
                }
            }
        }
    }

    private func valueForMetric(_ point: MetricDataPoint) -> Double {
        switch selectedMetric {
        case .cpu: return point.cpuUsage
        case .memory: return point.memoryUsage
        case .network: return point.networkDownload + point.networkUpload
        case .disk: return point.diskRead + point.diskWrite
        }
    }
}

// MARK: - Statistics Panel

struct StatisticsPanel: View {
    let dataPoints: [MetricDataPoint]

    var body: some View {
        GlassPanel(title: "Statistics", icon: "chart.bar") {
            if dataPoints.isEmpty {
                Text("No data available")
                    .font(.caption)
                    .foregroundColor(.secondary)
            } else {
                HStack(spacing: 24) {
                    StatColumn(
                        title: "CPU",
                        average: avgCPU,
                        max: maxCPU,
                        unit: "%",
                        color: .blue
                    )

                    Divider()

                    StatColumn(
                        title: "Memory",
                        average: avgMemory,
                        max: maxMemory,
                        unit: "%",
                        color: .green
                    )

                    Divider()

                    StatColumn(
                        title: "Network",
                        average: avgNetwork,
                        max: maxNetwork,
                        unit: "/s",
                        color: .orange,
                        formatAsBytes: true
                    )

                    Divider()

                    StatColumn(
                        title: "Disk I/O",
                        average: avgDisk,
                        max: maxDisk,
                        unit: "/s",
                        color: .purple,
                        formatAsBytes: true
                    )
                }
            }
        }
    }

    private var avgCPU: Double { dataPoints.map(\.cpuUsage).reduce(0, +) / Double(max(dataPoints.count, 1)) }
    private var maxCPU: Double { dataPoints.map(\.cpuUsage).max() ?? 0 }
    private var avgMemory: Double { dataPoints.map(\.memoryUsage).reduce(0, +) / Double(max(dataPoints.count, 1)) }
    private var maxMemory: Double { dataPoints.map(\.memoryUsage).max() ?? 0 }
    private var avgNetwork: Double { dataPoints.map { $0.networkUpload + $0.networkDownload }.reduce(0, +) / Double(max(dataPoints.count, 1)) }
    private var maxNetwork: Double { dataPoints.map { $0.networkUpload + $0.networkDownload }.max() ?? 0 }
    private var avgDisk: Double { dataPoints.map { $0.diskRead + $0.diskWrite }.reduce(0, +) / Double(max(dataPoints.count, 1)) }
    private var maxDisk: Double { dataPoints.map { $0.diskRead + $0.diskWrite }.max() ?? 0 }
}

struct StatColumn: View {
    let title: String
    let average: Double
    let max: Double
    let unit: String
    let color: Color
    var formatAsBytes: Bool = false

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(title)
                .font(.caption)
                .foregroundColor(.secondary)

            VStack(alignment: .leading, spacing: 4) {
                HStack {
                    Text("Avg:")
                        .font(.caption2)
                        .foregroundColor(.secondary)
                    Text(formattedValue(average))
                        .font(.caption)
                        .fontWeight(.medium)
                        .foregroundColor(color)
                }

                HStack {
                    Text("Max:")
                        .font(.caption2)
                        .foregroundColor(.secondary)
                    Text(formattedValue(max))
                        .font(.caption)
                        .fontWeight(.medium)
                        .foregroundColor(color)
                }
            }
        }
        .frame(maxWidth: .infinity)
    }

    private func formattedValue(_ value: Double) -> String {
        if formatAsBytes {
            return ByteFormatter.formatSpeed(value)
        }
        return String(format: "%.1f%@", value, unit)
    }
}

// MARK: - Session Reports Panel

struct SessionReportsPanel: View {
    let sessions: [SessionSummary]
    let onSelect: (SessionSummary) -> Void

    var body: some View {
        GlassPanel(title: "Session Reports", icon: "doc.text") {
            if sessions.isEmpty {
                Text("No session reports yet")
                    .font(.caption)
                    .foregroundColor(.secondary)
            } else {
                VStack(spacing: 8) {
                    ForEach(sessions.prefix(5)) { session in
                        SessionRow(session: session)
                            .onTapGesture {
                                onSelect(session)
                            }
                    }
                }
            }
        }
    }
}

struct SessionRow: View {
    let session: SessionSummary

    private let dateFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateStyle = .short
        f.timeStyle = .short
        return f
    }()

    var body: some View {
        HStack {
            VStack(alignment: .leading, spacing: 2) {
                Text(dateFormatter.string(from: session.startTime))
                    .font(.subheadline)
                Text("Duration: \(session.formattedDuration)")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }

            Spacer()

            HStack(spacing: 16) {
                VStack(alignment: .trailing, spacing: 2) {
                    Text("CPU")
                        .font(.caption2)
                        .foregroundColor(.secondary)
                    Text(String(format: "%.0f%%", session.avgCPU))
                        .font(.caption)
                        .fontWeight(.medium)
                }

                VStack(alignment: .trailing, spacing: 2) {
                    Text("Memory")
                        .font(.caption2)
                        .foregroundColor(.secondary)
                    Text(String(format: "%.0f%%", session.avgMemory))
                        .font(.caption)
                        .fontWeight(.medium)
                }

                if session.alertCount > 0 {
                    HStack(spacing: 2) {
                        Image(systemName: "bell.badge")
                            .font(.caption)
                            .foregroundColor(.orange)
                        Text("\(session.alertCount)")
                            .font(.caption)
                    }
                }
            }
        }
        .padding(8)
        .background(Color.primary.opacity(0.03))
        .cornerRadius(6)
    }
}

// MARK: - Session Detail View

struct SessionDetailView: View {
    let session: SessionSummary
    @Environment(\.dismiss) private var dismiss

    private let dateFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateStyle = .medium
        f.timeStyle = .short
        return f
    }()

    var body: some View {
        VStack(spacing: 16) {
            HStack {
                Text("Session Report")
                    .font(.headline)
                Spacer()
                Button("Close") { dismiss() }
            }

            Divider()

            VStack(alignment: .leading, spacing: 12) {
                DetailItem(label: "Start", value: dateFormatter.string(from: session.startTime))
                DetailItem(label: "End", value: dateFormatter.string(from: session.endTime))
                DetailItem(label: "Duration", value: session.formattedDuration)

                Divider()

                Text("Performance")
                    .font(.subheadline)
                    .fontWeight(.medium)

                HStack(spacing: 24) {
                    VStack(alignment: .leading, spacing: 4) {
                        DetailItem(label: "Avg CPU", value: String(format: "%.1f%%", session.avgCPU))
                        DetailItem(label: "Max CPU", value: String(format: "%.1f%%", session.maxCPU))
                    }

                    VStack(alignment: .leading, spacing: 4) {
                        DetailItem(label: "Avg Memory", value: String(format: "%.1f%%", session.avgMemory))
                        DetailItem(label: "Max Memory", value: String(format: "%.1f%%", session.maxMemory))
                    }
                }

                Divider()

                Text("Network & Disk")
                    .font(.subheadline)
                    .fontWeight(.medium)

                DetailItem(label: "Total Upload", value: ByteFormatter.formatBytes(session.totalNetworkUpload))
                DetailItem(label: "Total Download", value: ByteFormatter.formatBytes(session.totalNetworkDownload))
                DetailItem(label: "Total Disk Read", value: ByteFormatter.formatBytes(session.totalDiskRead))
                DetailItem(label: "Total Disk Write", value: ByteFormatter.formatBytes(session.totalDiskWrite))

                if session.alertCount > 0 {
                    Divider()
                    DetailItem(label: "Alerts Triggered", value: "\(session.alertCount)")
                }

                if !session.topProcesses.isEmpty {
                    Divider()
                    Text("Top Processes")
                        .font(.subheadline)
                        .fontWeight(.medium)
                    ForEach(session.topProcesses, id: \.self) { process in
                        Text("• \(process)")
                            .font(.caption)
                    }
                }
            }

            Spacer()
        }
        .padding()
        .frame(width: 400, height: 500)
    }
}

struct DetailItem: View {
    let label: String
    let value: String

    var body: some View {
        HStack {
            Text(label)
                .font(.caption)
                .foregroundColor(.secondary)
            Spacer()
            Text(value)
                .font(.caption)
                .fontWeight(.medium)
        }
    }
}

// MARK: - Export Panel

struct ExportPanel: View {
    let selectedRange: TimeRange
    let onExport: (ExportFormat) -> Void

    var body: some View {
        GlassPanel(title: "Export", icon: "square.and.arrow.up") {
            HStack(spacing: 16) {
                Text("Export \(selectedRange.rawValue) data:")
                    .font(.caption)
                    .foregroundColor(.secondary)

                Spacer()

                ForEach(ExportFormat.allCases, id: \.self) { format in
                    Button {
                        onExport(format)
                    } label: {
                        HStack(spacing: 4) {
                            Image(systemName: format.icon)
                                .font(.caption)
                            Text(format.rawValue)
                                .font(.caption)
                        }
                        .contentShape(Rectangle())
                    }
                    .buttonStyle(.borderless)
                    .padding(.horizontal, 10)
                    .padding(.vertical, 6)
                    .background(Color.accentColor.opacity(0.1))
                    .foregroundColor(.accentColor)
                    .cornerRadius(6)
                }
            }
        }
    }
}

// MARK: - Preview

#Preview {
    HistoryView()
        .frame(width: 900, height: 700)
}
